# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WorldCup2022CliDashboard < Formula
  desc ""
  homepage "https://github.com/cedricblondeau/world-cup-2022-cli-dashboard"
  version "1.2.0"
  license "MIT"

  on_macos do
    url "https://github.com/cedricblondeau/world-cup-2022-cli-dashboard/releases/download/v1.2.0/world-cup-2022-cli-dashboard_1.2.0_Darwin_all.tar.gz"
    sha256 "c755620ab682eee4b9183671a8430f04acace0d610efbe1a5dacff6a3538190d"

    def install
      bin.install "world-cup-2022-cli-dashboard"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cedricblondeau/world-cup-2022-cli-dashboard/releases/download/v1.2.0/world-cup-2022-cli-dashboard_1.2.0_Linux_arm64.tar.gz"
      sha256 "a64a09fa0a67a373b6765defeb5337cc65c5eb18d26cfc8c2f08b84216fe816d"

      def install
        bin.install "world-cup-2022-cli-dashboard"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cedricblondeau/world-cup-2022-cli-dashboard/releases/download/v1.2.0/world-cup-2022-cli-dashboard_1.2.0_Linux_x86_64.tar.gz"
      sha256 "d754a7bfb3c88430d8f4a5692f73b46d4f162a6fbc7a9022e9cd1271c304b402"

      def install
        bin.install "world-cup-2022-cli-dashboard"
      end
    end
  end
end
